# Generated by Django 3.1.5 on 2021-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
    ]
